version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: quiz-oracle-db
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=QUIZDB
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test:
        [
          "CMD",
          "sqlplus",
          "-L",
          "system/oracle@//localhost:1521/QUIZDB",
          "AS",
          "SYSDBA",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # llama-solver:
  #   image: ghcr.io/ggerganov/llama.cpp:server
  #   container_name: quiz-llama-solver
  #   platform: linux/amd64
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./models:/models
  #   command: --model /models/gemma-2b-it-q4_k_m.gguf --host 0.0.0.0 --port 8080
  #   environment:
  #     - LLAMA_SERVER_HOST=0.0.0.0
  #     - LLAMA_SERVER_PORT=8080
  #   depends_on:
  #     oracle-db:
  #       condition: service_healthy

  # llama-generator:
  #   image: ghcr.io/ggerganov/llama.cpp:server
  #   container_name: quiz-llama-generator
  #   platform: linux/amd64
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - ./models:/models
  #   command: --model /models/gemma-2b-it-q4_k_m.gguf --host 0.0.0.0 --port 8080
  #   environment:
  #     - LLAMA_SERVER_HOST=0.0.0.0
  #     - LLAMA_SERVER_PORT=8080
  #   depends_on:
  #     oracle-db:
  #       condition: service_healthy

  redis:
    image: "redis:alpine"
    container_name: quiz-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  oracle-data:
    name: quiz-oracle-data
  redis_data: # Define the redis_data volume
    name: quiz-redis-data
