package domain

import (
	"fmt"
	"strings"
	"time"
)

// ValidationError represents a validation error
type ValidationError struct {
	message string
}

func (e *ValidationError) Error() string {
	return e.message
}

func NewValidationError(message string) error {
	return &ValidationError{message: message}
}

// NotFoundError represents a not found error
type NotFoundError struct {
	message string
}

func (e *NotFoundError) Error() string {
	return e.message
}

// Category represents a quiz category
type Category struct {
	ID            string
	Name          string
	Description   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	SubCategories []*SubCategory
}

// NewCategory creates a new Category instance
func NewCategory(name, description string) *Category {
	now := time.Now()
	return &Category{
		Name:        name,
		Description: description,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
}

// Validate validates the category
func (c *Category) Validate() error {
	if c.Name == "" {
		return NewValidationError("name is required")
	}
	return nil
}

// SubCategory represents a subcategory under a main category
type SubCategory struct {
	ID          string
	CategoryID  string
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// NewSubCategory creates a new SubCategory instance
func NewSubCategory(categoryID string, name, description string) *SubCategory {
	now := time.Now()
	return &SubCategory{
		CategoryID:  categoryID,
		Name:        name,
		Description: description,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
}

// Validate validates the subcategory
func (s *SubCategory) Validate() error {
	if s.CategoryID == "" {
		return NewValidationError("category ID is required")
	}
	if s.Name == "" {
		return NewValidationError("name is required")
	}
	return nil
}

// Quiz represents a quiz in the domain
type Quiz struct {
	ID            string
	Question      string
	ModelAnswers  []string // Model answers
	Keywords      []string // Keywords for similarity matching
	Difficulty    int      // Difficulty (1: Easy, 2: Medium, 3: Hard)
	SubCategoryID string   // FK to SubCategory
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// NewQuiz creates a new Quiz instance
func NewQuiz(question string, modelAnswers []string, keywords []string, difficulty int, subCategoryID string) *Quiz {
	now := time.Now()
	return &Quiz{
		Question:      question,
		ModelAnswers:  modelAnswers,
		Keywords:      keywords,
		Difficulty:    difficulty,
		SubCategoryID: subCategoryID,
		CreatedAt:     now,
		UpdatedAt:     now,
	}
}

// DifficultyToString converts the difficulty level to a string representation
func DifficultyToInt(diff string) int {
	switch strings.ToLower(diff) {
	case "easy":
		return 1
	case "medium":
		return 2
	case "hard":
		return 3
	default:
		return 1
	}
}

func (q *Quiz) DifficultyToString() string {
	switch q.Difficulty {
	case 1:
		return "easy"
	case 2:
		return "medium"
	case 3:
		return "hard"
	default:
		return "easy"
	}
}

// Validate validates the quiz
func (q *Quiz) Validate() error {
	if q.Question == "" {
		return NewValidationError("question is required")
	}
	if len(q.ModelAnswers) == 0 {
		return NewValidationError("at least one model answer is required")
	}
	return nil
}

// Answer represents a user's answer to a quiz
// @Description Detailed result of a user's answer evaluation
type Answer struct {
	ID             string
	QuizID         string
	UserAnswer     string   // Descriptive answer
	Score          float64  // Score between 0.0 and 1.0
	Explanation    string   // Feedback generated by LLM
	KeywordMatches []string // Matched keywords
	Completeness   float64  // Answer completeness (0.0 ~ 1.0)
	Relevance      float64  // Answer relevance (0.0 ~ 1.0)
	Accuracy       float64  // Answer accuracy (0.0 ~ 1.0)
	AnsweredAt     time.Time
}

// NewAnswer creates a new Answer instance
func NewAnswer(quizID string, userAnswer string) *Answer {
	return &Answer{
		QuizID:     quizID,
		UserAnswer: userAnswer,
		AnsweredAt: time.Now(),
	}
}

// Validate validates the answer
func (a *Answer) Validate() error {
	if a.QuizID == "" {
		return NewValidationError("quiz ID is required")
	}
	if a.UserAnswer == "" {
		return NewValidationError("user answer is required")
	}
	return nil
}

// QuizEvaluation represents the evaluation criteria for a quiz
type QuizEvaluation struct {
	ID              string
	QuizID          string
	MinimumKeywords int      // Minimum required number of keywords
	RequiredTopics  []string // Required topics to include
	ScoreRanges     []string // Criteria per score range
	SampleAnswers   []string // Sample answers
	RubricDetails   string   // Detailed explanation of scoring rubric
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// NewQuizEvaluation creates a new QuizEvaluation instance
func NewQuizEvaluation(
	quizID string,
	minKeywords int,
	requiredTopics []string,
	sampleAnswers []string,
	rubricDetails string,
) *QuizEvaluation {
	now := time.Now()
	return &QuizEvaluation{
		QuizID:          quizID,
		MinimumKeywords: minKeywords,
		RequiredTopics:  requiredTopics,
		SampleAnswers:   sampleAnswers,
		RubricDetails:   rubricDetails,
		ScoreRanges:     []string{"0-0.3", "0.3-0.6", "0.6-0.8", "0.8-1.0"},
		CreatedAt:       now,
		UpdatedAt:       now,
	}
}

// Validate validates the quiz evaluation
func (e *QuizEvaluation) Validate() error {
	if e.QuizID == "" {
		return NewValidationError("quiz ID is required")
	}
	if e.MinimumKeywords == 0 {
		return NewValidationError("minimum keywords is required")
	}
	if len(e.RequiredTopics) == 0 {
		return NewValidationError("required topics are required")
	}
	if len(e.ScoreRanges) == 0 {
		return NewValidationError("score ranges are required")
	}
	if len(e.SampleAnswers) == 0 {
		return NewValidationError("sample answers are required")
	}
	if e.RubricDetails == "" {
		return NewValidationError("rubric details are required")
	}
	return nil
}

// InternalError represents an internal error
type InternalError struct {
	message string
	cause   error
}

func (e *InternalError) Error() string {
	if e.cause != nil {
		return fmt.Sprintf("%s: %v", e.message, e.cause)
	}
	return e.message
}

// InvalidCategoryError represents an invalid category error
type InvalidCategoryError struct {
	category string
}

func (e *InvalidCategoryError) Error() string {
	return fmt.Sprintf("invalid category: %s", e.category)
}

// QuizNotFoundError represents a quiz not found error
type QuizNotFoundError struct {
	quizID string
}

func (e *QuizNotFoundError) Error() string {
	return fmt.Sprintf("quiz not found: %s", e.quizID)
}

// LLMServiceError represents an LLM service error
type LLMServiceError struct {
	cause error
}

func (e *LLMServiceError) Error() string {
	return fmt.Sprintf("LLM service error: %v", e.cause)
}
